name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file dockerfile --tag nawho/hello:dev

    - name: Run node project
      run: node index.js

    - name: Push docker image to dockerhub
      run: docker push nawho/hello:dev
