name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: node:18.15.0

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file dockerfile --tag nawho/hello:$(date +%s)
